name: Create env file
  run: |
    touch .env
    echo REACT_APP_EMAILJS_PUBLIC_KEY =${{ vars.REACT_APP_EMAILJS_PUBLIC_KEY }} >> .env
    echo REACT_APP_EMAILJS_SERVICE_ID =${{ vars.REACT_APP_EMAILJS_SERVICE_ID }} >> .env
    echo REACT_APP_EMAILJS_TEMPLATE_ID =${{ vars.REACT_APP_EMAILJS_TEMPLATE_ID }} >> .env
    cat .env