name: Create env file

on:
  push:

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Creates .env file
        run: |
          touch .env
          echo REACT_APP_EMAILJS_PUBLIC_KEY =${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }} >> .env
          echo REACT_APP_EMAILJS_SERVICE_ID =${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }} >> .env
          echo REACT_APP_EMAILJS_TEMPLATE_ID =${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }} >> .env
          cat .env
